version: "3"

services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:4100"
    volumes:
      - .:/usr/app
    links:
      - "db:database"
  db:
    container_name: db
    image: tutum/mongodb
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      - AUTH=no
